"""initial schema

Revision ID: 7de3e6dbe2d9
Revises: 
Create Date: 2026-06-04 02:32:02.441335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7de3e6dbe2d9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amazon_entity_id', sa.String(length=64), nullable=True),
    sa.Column('entity_type', sa.Enum('CAMPAIGN', 'AD_GROUP', 'KEYWORD', name='adentitytype'), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('current_bid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('daily_budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_brand_awareness', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['ad_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ad_entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ad_entities_amazon_entity_id'), ['amazon_entity_id'], unique=False)

    op.create_table('approval_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('approval_type', sa.Enum('DAILY_SHIPMENT', 'SUPPLIER_PO', 'LISTING', 'AD_BID', name='approvaltype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approvalstatus'), nullable=False),
    sa.Column('ref_type', sa.String(length=32), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.String(length=64), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_tasks_approval_type'), ['approval_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_tasks_status'), ['status'], unique=False)

    op.create_table('catalog_sync_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('new_products', sa.Integer(), nullable=False),
    sa.Column('discontinued', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('jan', sa.String(length=20), nullable=True),
    sa.Column('asin', sa.String(length=20), nullable=True),
    sa.Column('manufacturer', sa.String(length=128), nullable=True),
    sa.Column('brand', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('spec', sa.JSON(), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('list_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'DISCONTINUED', name='productstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_asin'), ['asin'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_jan'), ['jan'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_sku'), ['sku'], unique=True)
        batch_op.create_index(batch_op.f('ix_products_status'), ['status'], unique=False)

    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amazon_po_number', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'MATCHING', 'PARTIALLY_BACKORDERED', 'READY_TO_SHIP', 'PACKED', 'SHIPPED', 'INVOICED', 'CLOSED', name='orderstatus'), nullable=False),
    sa.Column('ship_to', sa.String(length=255), nullable=True),
    sa.Column('asn_id', sa.String(length=64), nullable=True),
    sa.Column('invoice_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_orders_amazon_po_number'), ['amazon_po_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_purchase_orders_status'), ['status'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('two_factor_method', sa.Enum('EMAIL', 'SMS', name='twofactormethod'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('ad_metric_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_entity_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('spend', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sales', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('orders', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ad_entity_id'], ['ad_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ad_metric_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ad_metric_snapshots_ad_entity_id'), ['ad_entity_id'], unique=False)

    op.create_table('bid_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_entity_id', sa.Integer(), nullable=False),
    sa.Column('current_bid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('recommended_bid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('measured_acos', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PROPOSED', 'APPROVED', 'REJECTED', 'APPLIED', name='bidrecommendationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ad_entity_id'], ['ad_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bid_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bid_recommendations_ad_entity_id'), ['ad_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bid_recommendations_status'), ['status'], unique=False)

    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=32), nullable=False),
    sa.Column('on_hand', sa.Integer(), nullable=False),
    sa.Column('allocated', sa.Integer(), nullable=False),
    sa.Column('reorder_point', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'location', name='uq_inv_product_location')
    )
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_items_product_id'), ['product_id'], unique=False)

    op.create_table('inventory_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.Enum('INBOUND', 'ALLOCATE', 'RELEASE', 'OUTBOUND', 'ADJUST', name='movementtype'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('ref_type', sa.String(length=32), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_movements_product_id'), ['product_id'], unique=False)

    op.create_table('listing_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('bullet_points', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('GENERATING', 'PENDING_APPROVAL', 'APPROVED', 'PUBLISHED', 'REJECTED', name='listingdraftstatus'), nullable=False),
    sa.Column('generated_by', sa.String(length=64), nullable=True),
    sa.Column('published_asin', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listing_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listing_drafts_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_listing_drafts_status'), ['status'], unique=False)

    op.create_table('login_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_uid', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('method', sa.Enum('EMAIL', 'SMS', name='twofactormethod'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_challenges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_challenges_challenge_uid'), ['challenge_uid'], unique=True)
        batch_op.create_index(batch_op.f('ix_login_challenges_user_id'), ['user_id'], unique=False)

    op.create_table('order_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty_ordered', sa.Integer(), nullable=False),
    sa.Column('qty_confirmed', sa.Integer(), nullable=False),
    sa.Column('qty_backordered', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ALLOCATED', 'BACKORDERED', 'PACKED', 'SHIPPED', name='orderlinestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_lines_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_lines_product_id'), ['product_id'], unique=False)

    op.create_table('supplier_purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_name', sa.String(length=128), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('related_order_line_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'RECEIVED', 'CANCELLED', name='supplierpostatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['related_order_line_id'], ['order_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_purchase_orders_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_purchase_orders_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_purchase_orders_status'))
        batch_op.drop_index(batch_op.f('ix_supplier_purchase_orders_product_id'))

    op.drop_table('supplier_purchase_orders')
    with op.batch_alter_table('order_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_lines_product_id'))
        batch_op.drop_index(batch_op.f('ix_order_lines_order_id'))

    op.drop_table('order_lines')
    with op.batch_alter_table('login_challenges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_challenges_user_id'))
        batch_op.drop_index(batch_op.f('ix_login_challenges_challenge_uid'))

    op.drop_table('login_challenges')
    with op.batch_alter_table('listing_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listing_drafts_status'))
        batch_op.drop_index(batch_op.f('ix_listing_drafts_product_id'))

    op.drop_table('listing_drafts')
    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_movements_product_id'))

    op.drop_table('inventory_movements')
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_items_product_id'))

    op.drop_table('inventory_items')
    with op.batch_alter_table('bid_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bid_recommendations_status'))
        batch_op.drop_index(batch_op.f('ix_bid_recommendations_ad_entity_id'))

    op.drop_table('bid_recommendations')
    with op.batch_alter_table('ad_metric_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ad_metric_snapshots_ad_entity_id'))

    op.drop_table('ad_metric_snapshots')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_status'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_amazon_po_number'))

    op.drop_table('purchase_orders')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_status'))
        batch_op.drop_index(batch_op.f('ix_products_sku'))
        batch_op.drop_index(batch_op.f('ix_products_jan'))
        batch_op.drop_index(batch_op.f('ix_products_asin'))

    op.drop_table('products')
    op.drop_table('catalog_sync_jobs')
    with op.batch_alter_table('approval_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_approval_tasks_approval_type'))

    op.drop_table('approval_tasks')
    with op.batch_alter_table('ad_entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ad_entities_amazon_entity_id'))

    op.drop_table('ad_entities')
    # ### end Alembic commands ###
